### ISSUE TITLE
World.setSize will set delay to 100

### ISSUE THREAD

**Issue by Danghor** [tudalgo/fopbot#15]
Since World.setSize creates a new KarelWorld, all settings of the old KarelWorld will be lost after calling the method. For example, it will reset the delay to the default value of 100, even if a delay of 0 was set before. Since the method is named setSize, I would it expect to do no more than setting the size of the world.

The behavior can be tested using the following code snipped:

```java
World.setDelay(0);
System.out.println(World.getDelay()); // 0
World.setSize(3, 3);
System.out.println(World.getDelay()); // actual: 100, would expect 0 instead
```

**Comment by zentox** [comment]
Mir ist ebenfalls aufgefallen, dass beim wiederholten Aufruf von `World.setSize(3, 3);`ein neues Fenster erzeugt wird. Ist das beabsichtigt?

````java
World.setSize(10,10);
World.setVisible(true);
World.setSize(10,10);
World.setVisible(true);
````
