### ISSUE TITLE
Repeated call of World.setSize(x,y) creates a new window

### ISSUE THREAD

**Issue by dst97** [tudalgo/fopbot#21]
Mir ist ebenfalls aufgefallen, dass beim wiederholten Aufruf von `World.setSize(x, y);`ein neues Fenster erzeugt wird. Ist das beabsichtigt?

````java
World.setSize(10,10);
World.setVisible(true);
World.setSize(10,10);
World.setVisible(true);
````

_Originally posted by @zentox in https://github.com/tudalgo/fopbot/issues/15#issuecomment-1242722578_

**Comment by dst97** [comment]
This behavior seems to be indended, but can be replaced in a future version.

**Comment by Rdeisenroth** [comment]
Intendet behavior.
