### ISSUE TITLE
Direction Enum

### ISSUE THREAD

**Issue by Tscheb** [tudalgo/fopbot#26]
The possible directions int the Enum Direction are ordered clockwise, with `UP` as the firs value.

So the integer representation of the values you get with `Direction.myDirection.ordinal` are as follows:

- `UP` is represented by 0
- `RIGHT` is represented by 1
- `DOWN` is represented by 2
- `LEFT` is represented by 3

After a single call of `turnLeft()` a Robot changes direction from `UP` (represented as 0) to `LEFT` ( represented as 3) and after calling `turnLeft();` three times, a robot changes direction from `UP` to `RIGHT` (represented as 1).
Wouldn't a counterclockwise order with `LEFT` -> 1 and `RIGHT` -> 3 be more consistent?

**Comment by Rdeisenroth** [comment]
We still decided to leave it like this for compatibility reasons, but using the new dX and dY it should make modulo math easier.
