### ISSUE TITLE
Make KarelWorld extendable

### ISSUE THREAD

**Issue by Rdeisenroth** [tudalgo/fopbot#30]
Since https://github.com/tudalgo/fopbot/commit/78586d847d3f0eceffda3250ccdce2ede477f011, it is no longer possible to extend the Gui functionality for an exercise (in my case, i would like to use keyboard events). So first of all what's the reasoning behind that? If students wanted to mess with the GUI so badly they could still do so by extending and replacing the static KarelWorld instance. Regardless i think it would make sense to make these kinds of attributes protected instead of private for KarelWorld. In my Oppinion having a Getter also wouldn't hurt for the gui.

**Comment by alexstaeding** [comment]
IIRC, the headless version (used for grading) does not have any GUI code so that wouldn't work
